Repository lmtsufape/vida-agroecologica-gestao-web-v2, pull requests merged in 2024-11, with the labels that each got.

#55 (chore):enhance span labels
  src/app/usuarios/cadastrar/styles.module.scss
  src/app/usuarios/editar/[id]/styles.module.scss
  src/components/Multiselect/index.tsx
Labels: enhancement

#57 (chore):new card edit user
  src/app/associacoes/page.tsx
  src/components/Menubuttons/index.tsx
  src/utils/session.tsx
Labels: enhancement

#59 Correções de problemas do lint
  src/app/recuperar-senha/components/ResetPassword.tsx
  src/components/Anexos/index.tsx
  src/components/Ata/index.tsx
  src/components/Navbar/index.tsx
  src/services/associations.ts
  src/services/bairro.ts
  src/services/ocs.ts
  src/services/reunioes.ts
  src/services/user.ts
Labels: good first issue

#67 (fix):show data input
  .vscode/launch.json
  src/app/reunioes/editar/[id]/page.tsx
Labels: bug

#68 (fix):show data input
  src/app/associacoes/editar/[id]/page.tsx
Labels: bug
